<?php

return array(
	/*
	'sample1'=>array(
		'id_tata_pamong' => '',
		'id_prodi' => '',
		'id_administrasi' => '',
		'sistem_tata_pamong' => '',
		'kepemimpinan' => '',
		'sistem_pengelolaan' => '',
		'penjaminan_mutu' => '',
		'umpan_balik_dosen' => '',
		'tindak_lanjut_dosen' => '',
		'umpan_balik_mhs' => '',
		'tindak_lanjut_mhs' => '',
		'umpan_balik_alumni' => '',
		'tindak_lanjut_alumni' => '',
		'umpan_balik_lulusan' => '',
		'tindak_lanjut_lulusan' => '',
		'animo_calon_mhs' => '',
		'mutu_manajemen' => '',
		'mutu_lulusan' => '',
		'kerjasama_kemitraan' => '',
		'hibah_kompetitif' => '',
		'sumber_data' => '',
		'lampiran' => '',
	),
	'sample2'=>array(
		'id_tata_pamong' => '',
		'id_prodi' => '',
		'id_administrasi' => '',
		'sistem_tata_pamong' => '',
		'kepemimpinan' => '',
		'sistem_pengelolaan' => '',
		'penjaminan_mutu' => '',
		'umpan_balik_dosen' => '',
		'tindak_lanjut_dosen' => '',
		'umpan_balik_mhs' => '',
		'tindak_lanjut_mhs' => '',
		'umpan_balik_alumni' => '',
		'tindak_lanjut_alumni' => '',
		'umpan_balik_lulusan' => '',
		'tindak_lanjut_lulusan' => '',
		'animo_calon_mhs' => '',
		'mutu_manajemen' => '',
		'mutu_lulusan' => '',
		'kerjasama_kemitraan' => '',
		'hibah_kompetitif' => '',
		'sumber_data' => '',
		'lampiran' => '',
	),
	*/
);
